export const SELECT_INTERESTS = 'SELECT_INTERESTS';
export const SELECT_HAIR_STYLE = 'SELECT_HAIR_STYLE';
export const SELECT_HAIR_COLOR = 'SELECT_HAIR_COLOR';
export const SELECT_TOP_CLOTHES = 'SELECT_TOP_CLOTHES';
export const SELECT_BOTTOM_CLOTHES = 'SELECT_BOTTOM_CLOTHES';
export const SELECT_SHOES = 'SELECT_SHOES';
